// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDku0UgxnM9khmi5I9OlbpHgKDz5LtV-F8',
    appId: '1:966116419979:web:e50d200a31e1606ee4e78e',
    messagingSenderId: '966116419979',
    projectId: 'doc-appoint-bea6b',
    authDomain: 'doc-appoint-bea6b.firebaseapp.com',
    storageBucket: 'doc-appoint-bea6b.appspot.com',
    measurementId: 'G-45GHFB2223',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9C029rzgyG73uym4j1Wb9NElMAW1sBcc',
    appId: '1:966116419979:android:eae637384b8a649fe4e78e',
    messagingSenderId: '966116419979',
    projectId: 'doc-appoint-bea6b',
    storageBucket: 'doc-appoint-bea6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBycfuFXs1j8bMBlge2aPd1Ht4hxK-AZoo',
    appId: '1:966116419979:ios:e5ae2d610cb602fce4e78e',
    messagingSenderId: '966116419979',
    projectId: 'doc-appoint-bea6b',
    storageBucket: 'doc-appoint-bea6b.appspot.com',
    iosBundleId: 'com.example.docAppoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBycfuFXs1j8bMBlge2aPd1Ht4hxK-AZoo',
    appId: '1:966116419979:ios:e5ae2d610cb602fce4e78e',
    messagingSenderId: '966116419979',
    projectId: 'doc-appoint-bea6b',
    storageBucket: 'doc-appoint-bea6b.appspot.com',
    iosBundleId: 'com.example.docAppoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDku0UgxnM9khmi5I9OlbpHgKDz5LtV-F8',
    appId: '1:966116419979:web:faf1467715155408e4e78e',
    messagingSenderId: '966116419979',
    projectId: 'doc-appoint-bea6b',
    authDomain: 'doc-appoint-bea6b.firebaseapp.com',
    storageBucket: 'doc-appoint-bea6b.appspot.com',
    measurementId: 'G-SKRCV17SMB',
  );
}
